"use client"

/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState, useEffect, useRef, useCallback, useMemo } from "react"
import { useRouter } from "next/navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  prepareSimulation,
  getPrepareStatus,
  getSimulationProfilesRealtime,
  getSimulationConfig,
  getSimulationConfigRealtime,
} from "@/lib/api/simulation"

// ─── Types ───────────────────────────────────────────────────────────
interface Profile {
  name?: string
  username?: string
  bio?: string
  persona?: string
  profession?: string
  entity_type?: string
  age?: number
  gender?: string
  country?: string
  mbti?: string
  interested_topics?: string[]
}

interface AgentConfig {
  agent_id: number
  entity_name: string
  entity_type: string
  stance: string
  active_hours?: number[]
  posts_per_hour?: number
  comments_per_hour?: number
  response_delay_min?: number
  response_delay_max?: number
  activity_level?: number
  sentiment_bias?: number
  influence_weight?: number
}

interface TimeConfig {
  total_simulation_hours?: number
  minutes_per_round?: number
  peak_hours?: number[]
  peak_activity_multiplier?: number
  work_hours?: number[]
  work_activity_multiplier?: number
  morning_hours?: number[]
  morning_activity_multiplier?: number
  off_peak_hours?: number[]
  off_peak_activity_multiplier?: number
  agents_per_hour_min?: number
  agents_per_hour_max?: number
}

interface PlatformConfig {
  recency_weight?: number
  popularity_weight?: number
  relevance_weight?: number
  viral_threshold?: number
  echo_chamber_strength?: number
}

interface EventConfig {
  narrative_direction?: string
  hot_topics?: string[]
  initial_posts?: {
    poster_type: string
    poster_agent_id: number
    content: string
  }[]
}

interface SimulationConfig {
  time_config?: TimeConfig
  agent_configs?: AgentConfig[]
  twitter_config?: PlatformConfig
  reddit_config?: PlatformConfig
  event_config?: EventConfig
  generation_reasoning?: string
}

interface Step2Props {
  simulationId: string
  projectData: any
  graphData: any
  systemLogs: { time: string; msg: string }[]
  onGoBack: () => void
  onNextStep: (params?: any) => void
  onAddLog: (msg: string) => void
  onUpdateStatus?: (status: string) => void
}

// ─── Component ───────────────────────────────────────────────────────
export default function Step2EnvSetup({
  simulationId,
  projectData,
  systemLogs,
  onGoBack,
  onNextStep,
  onAddLog,
  onUpdateStatus,
}: Step2Props) {
  const router = useRouter()
  const logRef = useRef<HTMLDivElement>(null)

  // Phase: 0=init, 1=generating profiles, 2=generating config, 3=orchestration, 4=ready
  const [phase, setPhase] = useState(0)
  const [taskId, setTaskId] = useState<string | null>(null)
  const [prepareProgress, setPrepareProgress] = useState(0)
  const [progressMessage, setProgressMessage] = useState("")
  const [currentStage, setCurrentStage] = useState("")
  const [profiles, setProfiles] = useState<Profile[]>([])
  const [expectedTotal, setExpectedTotal] = useState<number | null>(null)
  const [entityTypes, setEntityTypes] = useState<string[]>([])
  const [simulationConfig, setSimulationConfig] = useState<SimulationConfig | null>(null)
  const [selectedProfile, setSelectedProfile] = useState<Profile | null>(null)

  // Round config
  const [useCustomRounds, setUseCustomRounds] = useState(false)
  const [customMaxRounds, setCustomMaxRounds] = useState(40)

  // Polling refs
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const profilePollRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const configPollRef = useRef<ReturnType<typeof setInterval> | null>(null)

  // De-dup log tracking
  const lastLoggedMessageRef = useRef("")
  const lastLoggedProfileCountRef = useRef(0)
  const lastLoggedConfigStageRef = useRef("")

  // ─── Computed ────────────────────────────────────────────────────
  const autoGeneratedRounds = useMemo(() => {
    if (!simulationConfig?.time_config) return null
    const totalHours = simulationConfig.time_config.total_simulation_hours
    const minutesPerRound = simulationConfig.time_config.minutes_per_round
    if (!totalHours || !minutesPerRound) return null
    const calc = Math.floor((totalHours * 60) / minutesPerRound)
    return Math.max(calc, 40)
  }, [simulationConfig])

  const totalTopicsCount = useMemo(() => {
    return profiles.reduce((sum, p) => sum + (p.interested_topics?.length || 0), 0)
  }, [profiles])

  const getAgentUsername = useCallback(
    (agentId: number) => {
      if (profiles.length > agentId && agentId >= 0) {
        return profiles[agentId]?.username || `agent_${agentId}`
      }
      return `agent_${agentId}`
    },
    [profiles]
  )

  // ─── Auto-scroll logs ───────────────────────────────────────────
  useEffect(() => {
    if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight
  }, [systemLogs])

  // ─── Cleanup ────────────────────────────────────────────────────
  const stopAllPolling = useCallback(() => {
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
    if (profilePollRef.current) { clearInterval(profilePollRef.current); profilePollRef.current = null }
    if (configPollRef.current) { clearInterval(configPollRef.current); configPollRef.current = null }
  }, [])

  useEffect(() => { return () => stopAllPolling() }, [stopAllPolling])

  // ─── Stage watcher ──────────────────────────────────────────────
  useEffect(() => {
    if (currentStage === "generating_profiles" || currentStage === "\u751F\u6210Agent\u4EBA\u8BBE") {
      setPhase(1)
    } else if (currentStage === "generating_config" || currentStage === "\u751F\u6210\u6A21\u62DF\u914D\u7F6E") {
      if (!configPollRef.current) {
        onAddLog("Generating simulation configuration...")
        startConfigPolling()
      }
      setPhase(2)
    } else if (currentStage === "copying_scripts" || currentStage === "\u51C6\u5907\u6A21\u62DF\u811A\u672C") {
      setPhase(2)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentStage])

  // ─── Profile polling ────────────────────────────────────────────
  const fetchProfilesRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res: any = await getSimulationProfilesRealtime(simulationId, "reddit")
      if (res.success && res.data) {
        const newProfiles: Profile[] = res.data.profiles || []
        setProfiles(newProfiles)
        if (res.data.total_expected) setExpectedTotal(res.data.total_expected)

        // Extract entity types
        const types = new Set<string>()
        newProfiles.forEach((p) => { if (p.entity_type) types.add(p.entity_type) })
        setEntityTypes(Array.from(types))

        // Log profile progress (dedup)
        const count = newProfiles.length
        if (count > 0 && count !== lastLoggedProfileCountRef.current) {
          lastLoggedProfileCountRef.current = count
          const total = res.data.total_expected || "?"
          const latest = newProfiles[count - 1]
          const pName = latest?.name || latest?.username || `Agent_${count}`
          if (count === 1) onAddLog("Starting agent profile generation...")
          onAddLog(`-> Agent profile ${count}/${total}: ${pName} (${latest?.profession || "unknown"})`)
          if (res.data.total_expected && count >= res.data.total_expected) {
            onAddLog(`All ${count} agent profiles generated`)
          }
        }
      }
    } catch { /* ignore */ }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [simulationId])

  const startProfilePolling = useCallback(() => {
    if (profilePollRef.current) return
    profilePollRef.current = setInterval(fetchProfilesRealtime, 3000)
  }, [fetchProfilesRealtime])

  // ─── Config polling ─────────────────────────────────────────────
  const fetchConfigRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res: any = await getSimulationConfigRealtime(simulationId)
      if (res.success && res.data) {
        const data = res.data
        if (data.generation_stage && data.generation_stage !== lastLoggedConfigStageRef.current) {
          lastLoggedConfigStageRef.current = data.generation_stage
          if (data.generation_stage === "generating_profiles") onAddLog("Generating agent profile configuration...")
          else if (data.generation_stage === "generating_config") onAddLog("Calling LLM to generate simulation config parameters...")
        }
        if (data.config_generated && data.config) {
          setSimulationConfig(data.config)
          onAddLog("Simulation configuration generated")
          if (data.summary) {
            onAddLog(`  Agent count: ${data.summary.total_agents}`)
            onAddLog(`  Duration: ${data.summary.simulation_hours}h`)
            onAddLog(`  Initial posts: ${data.summary.initial_posts_count}`)
            onAddLog(`  Platforms: Twitter ${data.summary.has_twitter_config ? "OK" : "--"}, Reddit ${data.summary.has_reddit_config ? "OK" : "--"}`)
          }
          if (data.config.time_config) {
            const tc = data.config.time_config
            const totalRounds = Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round)
            onAddLog(`  Time: ${tc.minutes_per_round}min/round, ${totalRounds} rounds total`)
          }
          if (configPollRef.current) { clearInterval(configPollRef.current); configPollRef.current = null }
          setPhase(4)
          onAddLog("Environment setup complete, ready to start simulation")
          onUpdateStatus?.("completed")
        }
      }
    } catch { /* ignore */ }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [simulationId])

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const startConfigPolling = useCallback(() => {
    if (configPollRef.current) return
    configPollRef.current = setInterval(fetchConfigRealtime, 2000)
  }, [fetchConfigRealtime])

  // ─── Status polling ─────────────────────────────────────────────
  const pollPrepareStatus = useCallback(async () => {
    if (!taskId && !simulationId) return
    try {
      const res: any = await getPrepareStatus({ task_id: taskId || undefined, simulation_id: simulationId })
      if (res.success && res.data) {
        const data = res.data
        setPrepareProgress(data.progress || 0)
        setProgressMessage(data.message || "")

        if (data.progress_detail) {
          setCurrentStage(data.progress_detail.current_stage_name || "")
          const detail = data.progress_detail
          const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`
          if (logKey !== lastLoggedMessageRef.current && detail.item_description) {
            lastLoggedMessageRef.current = logKey
            const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`
            if (detail.total_items > 0) {
              onAddLog(`${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`)
            } else {
              onAddLog(`${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`)
            }
          }
        } else if (data.message) {
          const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
          if (match) setCurrentStage(match[3].trim())
          if (data.message !== lastLoggedMessageRef.current) {
            lastLoggedMessageRef.current = data.message
            onAddLog(data.message)
          }
        }

        if (data.status === "completed" || data.status === "ready" || data.already_prepared) {
          onAddLog("Preparation completed")
          if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
          if (profilePollRef.current) { clearInterval(profilePollRef.current); profilePollRef.current = null }
          await loadPreparedData()
        } else if (data.status === "failed") {
          onAddLog(`Preparation failed: ${data.error || "Unknown error"}`)
          if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
          if (profilePollRef.current) { clearInterval(profilePollRef.current); profilePollRef.current = null }
        }
      }
    } catch { /* ignore */ }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [taskId, simulationId])

  // ─── Load prepared data ─────────────────────────────────────────
  const loadPreparedData = useCallback(async () => {
    setPhase(2)
    onAddLog("Loading existing configuration data...")
    await fetchProfilesRealtime()
    onAddLog(`Loaded ${profiles.length} agent profiles`)
    try {
      const res: any = await getSimulationConfigRealtime(simulationId)
      if (res.success && res.data) {
        if (res.data.config_generated && res.data.config) {
          setSimulationConfig(res.data.config)
          onAddLog("Simulation configuration loaded")
          if (res.data.summary) {
            onAddLog(`  Agents: ${res.data.summary.total_agents}, Duration: ${res.data.summary.simulation_hours}h`)
          }
          setPhase(4)
          onUpdateStatus?.("completed")
        } else {
          onAddLog("Config still generating, starting poll...")
          startConfigPolling()
        }
      }
    } catch (err: any) {
      onAddLog(`Failed to load config: ${err.message}`)
      onUpdateStatus?.("error")
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [simulationId, fetchProfilesRealtime])

  // ─── Start preparation ──────────────────────────────────────────
  const startPrepare = useCallback(async () => {
    if (!simulationId) {
      onAddLog("Error: missing simulationId")
      onUpdateStatus?.("error")
      return
    }
    setPhase(1)
    onAddLog(`Simulation instance created: ${simulationId}`)
    onAddLog("Preparing simulation environment...")
    onUpdateStatus?.("processing")
    try {
      const res: any = await prepareSimulation({
        simulation_id: simulationId,
        use_llm_for_profiles: true,
        parallel_profile_count: 5,
      })
      if (res.success && res.data) {
        if (res.data.already_prepared) {
          onAddLog("Detected existing preparation, reusing")
          await loadPreparedData()
          return
        }
        setTaskId(res.data.task_id)
        onAddLog(`Prepare task started: ${res.data.task_id}`)
        if (res.data.expected_entities_count) {
          setExpectedTotal(res.data.expected_entities_count)
          onAddLog(`Found ${res.data.expected_entities_count} entities from knowledge graph`)
          if (res.data.entity_types?.length) {
            onAddLog(`  Entity types: ${res.data.entity_types.join(", ")}`)
          }
        }
        // Start polling
        pollRef.current = setInterval(pollPrepareStatus, 2000)
        pollPrepareStatus()
        startProfilePolling()
      } else {
        onAddLog(`Prepare failed: ${res.error || "Unknown error"}`)
        onUpdateStatus?.("error")
      }
    } catch (err: any) {
      onAddLog(`Prepare error: ${err.message}`)
      onUpdateStatus?.("error")
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [simulationId, pollPrepareStatus, startProfilePolling, loadPreparedData])

  // Auto-start on mount
  useEffect(() => {
    if (simulationId && phase === 0) {
      onAddLog("Step2 Environment setup initializing")
      startPrepare()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [simulationId])

  // ─── Handle start simulation ────────────────────────────────────
  const handleStartSimulation = () => {
    const params: any = {}
    if (useCustomRounds) {
      params.maxRounds = customMaxRounds
      onAddLog(`Starting simulation with custom rounds: ${customMaxRounds}`)
    } else {
      onAddLog(`Starting simulation with auto rounds: ${autoGeneratedRounds}`)
    }
    onNextStep(params)
  }

  // ─── Render helpers ─────────────────────────────────────────────
  const phaseClass = (step: number) =>
    `bg-white rounded-lg p-5 shadow-sm border transition-all ${phase === step ? "border-orange-500 shadow-[0_4px_12px_rgba(255,87,34,0.08)]" : phase > step ? "border-gray-200" : "border-gray-200"}`

  const stepNumClass = (step: number) =>
    `font-mono text-xl font-bold ${phase >= step ? "text-black" : "text-gray-300"}`

  return (
    <div className="h-full flex flex-col bg-[#FAFAFA] overflow-hidden">
      <div className="flex-1 overflow-y-auto p-6 space-y-5">

        {/* ═══ Step 01: Simulation Instance ═══ */}
        <div className={phaseClass(0)}>
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center gap-3">
              <span className={stepNumClass(0)}>01</span>
              <span className="font-semibold text-sm">Simulation Instance Initialization</span>
            </div>
            {phase > 0 ? <Badge variant="success">Complete</Badge> : <Badge variant="processing">Initializing</Badge>}
          </div>
          <p className="text-[10px] text-gray-400 font-mono mb-2">POST /api/simulation/create</p>
          <p className="text-xs text-gray-500 mb-4">Create simulation instance and pull world parameter templates</p>

          {simulationId && (
            <div className="bg-gray-50 rounded-md p-4 space-y-2.5">
              {[
                ["Project ID", projectData?.project_id],
                ["Graph ID", projectData?.graph_id],
                ["Simulation ID", simulationId],
                ["Task ID", taskId || "Async task completed"],
              ].map(([label, value]) => (
                <div key={label as string} className="flex justify-between items-center py-1.5 border-b border-dashed border-gray-200 last:border-b-0">
                  <span className="text-xs text-gray-500">{label}</span>
                  <span className="text-xs font-mono text-gray-700">{value as string}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* ═══ Step 02: Agent Profile Generation ═══ */}
        <div className={phaseClass(1)}>
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center gap-3">
              <span className={stepNumClass(1)}>02</span>
              <span className="font-semibold text-sm">Agent Profile Generation</span>
            </div>
            {phase > 1 ? (
              <Badge variant="success">Complete</Badge>
            ) : phase === 1 ? (
              <Badge variant="processing">{prepareProgress}%</Badge>
            ) : (
              <Badge variant="secondary">Waiting</Badge>
            )}
          </div>
          <p className="text-[10px] text-gray-400 font-mono mb-2">POST /api/simulation/prepare</p>
          <p className="text-xs text-gray-500 mb-4">
            Extract entities from knowledge graph, initialize agents, and give them unique behaviors and memories based on real-world seeds
          </p>

          {phase >= 1 && (
            <div className="mb-4">
              <Progress value={prepareProgress} className="h-2 mb-2" />
              <p className="text-xs text-gray-400">{progressMessage}</p>
            </div>
          )}

          {/* Stats Grid */}
          {profiles.length > 0 && (
            <div className="grid grid-cols-3 gap-3 bg-gray-50 p-4 rounded-md mb-4">
              <div className="text-center">
                <span className="block text-xl font-bold font-mono text-black">{profiles.length}</span>
                <span className="text-[9px] text-gray-400 uppercase mt-1 block">Current Agents</span>
              </div>
              <div className="text-center">
                <span className="block text-xl font-bold font-mono text-black">{expectedTotal || "-"}</span>
                <span className="text-[9px] text-gray-400 uppercase mt-1 block">Expected Total</span>
              </div>
              <div className="text-center">
                <span className="block text-xl font-bold font-mono text-black">{totalTopicsCount}</span>
                <span className="text-[9px] text-gray-400 uppercase mt-1 block">Related Topics</span>
              </div>
            </div>
          )}

          {/* Entity Type Badges */}
          {entityTypes.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mb-4">
              {entityTypes.map((type) => (
                <span key={type} className="text-[10px] bg-blue-50 text-blue-700 px-2 py-0.5 rounded">
                  {type}
                </span>
              ))}
            </div>
          )}

          {/* Profiles List */}
          {profiles.length > 0 && (
            <div className="border-t border-gray-200 pt-4">
              <div className="flex justify-between items-center mb-3">
                <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Generated Agent Profiles</span>
              </div>
              <div className="grid grid-cols-2 gap-3 max-h-[320px] overflow-y-auto pr-1">
                {profiles.map((profile, idx) => (
                  <div
                    key={idx}
                    className="bg-gray-50 border border-gray-200 rounded-md p-3.5 cursor-pointer transition-all hover:border-gray-400 hover:bg-white"
                    onClick={() => setSelectedProfile(profile)}
                  >
                    <div className="flex items-baseline gap-2 mb-1.5">
                      <span className="text-sm font-bold text-black">{profile.username || "Unknown"}</span>
                      <span className="font-mono text-[11px] text-gray-400">@{profile.name || `agent_${idx}`}</span>
                    </div>
                    <div className="mb-2">
                      <span className="text-[11px] text-gray-600 bg-gray-100 px-2 py-0.5 rounded">
                        {profile.profession || "Unknown profession"}
                      </span>
                    </div>
                    <p className="text-xs text-gray-500 leading-relaxed line-clamp-3 mb-2.5">
                      {profile.bio || "No bio available"}
                    </p>
                    {profile.interested_topics && profile.interested_topics.length > 0 && (
                      <div className="flex flex-wrap gap-1.5">
                        {profile.interested_topics.slice(0, 3).map((topic) => (
                          <span key={topic} className="text-[10px] text-blue-700 bg-blue-50 px-2 py-0.5 rounded-full">
                            {topic}
                          </span>
                        ))}
                        {profile.interested_topics.length > 3 && (
                          <span className="text-[10px] text-gray-400 py-0.5">
                            +{profile.interested_topics.length - 3}
                          </span>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* ═══ Step 03: Simulation Configuration ═══ */}
        <div className={phaseClass(2)}>
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center gap-3">
              <span className={stepNumClass(2)}>03</span>
              <span className="font-semibold text-sm">Dual-Platform Simulation Config</span>
            </div>
            {phase > 2 ? (
              <Badge variant="success">Complete</Badge>
            ) : phase === 2 ? (
              <Badge variant="processing">Generating</Badge>
            ) : (
              <Badge variant="secondary">Waiting</Badge>
            )}
          </div>
          <p className="text-[10px] text-gray-400 font-mono mb-2">POST /api/simulation/prepare</p>
          <p className="text-xs text-gray-500 mb-4">
            LLM intelligently configures world time flow, recommendation algorithms, individual activity patterns, posting frequency, and event triggers
          </p>

          {simulationConfig && (
            <div className="mt-4 space-y-4">

              {/* Time Config Grid */}
              {simulationConfig.time_config && (
                <div>
                  <div className="grid grid-cols-4 gap-3">
                    {[
                      ["Sim Duration", `${simulationConfig.time_config.total_simulation_hours || "-"}h`],
                      ["Per Round", `${simulationConfig.time_config.minutes_per_round || "-"}min`],
                      ["Total Rounds", `${simulationConfig.time_config.total_simulation_hours && simulationConfig.time_config.minutes_per_round ? Math.floor((simulationConfig.time_config.total_simulation_hours * 60) / simulationConfig.time_config.minutes_per_round) : "-"}`],
                      ["Agents/Hour", `${simulationConfig.time_config.agents_per_hour_min || "-"}-${simulationConfig.time_config.agents_per_hour_max || "-"}`],
                    ].map(([label, value]) => (
                      <div key={label as string} className="bg-gray-50 p-3 rounded-md">
                        <span className="text-[11px] text-gray-400 block">{label}</span>
                        <span className="font-mono text-base font-semibold text-gray-900">{value}</span>
                      </div>
                    ))}
                  </div>

                  {/* Time Periods */}
                  <div className="mt-3 space-y-2">
                    {[
                      {
                        label: "Peak Hours",
                        hours: simulationConfig.time_config.peak_hours?.join(":00, ") + ":00",
                        multiplier: simulationConfig.time_config.peak_activity_multiplier,
                      },
                      {
                        label: "Work Hours",
                        hours: `${simulationConfig.time_config.work_hours?.[0]}:00-${simulationConfig.time_config.work_hours?.slice(-1)[0]}:00`,
                        multiplier: simulationConfig.time_config.work_activity_multiplier,
                      },
                      {
                        label: "Morning Hours",
                        hours: `${simulationConfig.time_config.morning_hours?.[0]}:00-${simulationConfig.time_config.morning_hours?.slice(-1)[0]}:00`,
                        multiplier: simulationConfig.time_config.morning_activity_multiplier,
                      },
                      {
                        label: "Off-Peak",
                        hours: `${simulationConfig.time_config.off_peak_hours?.[0]}:00-${simulationConfig.time_config.off_peak_hours?.slice(-1)[0]}:00`,
                        multiplier: simulationConfig.time_config.off_peak_activity_multiplier,
                      },
                    ].map((period) => (
                      <div key={period.label} className="flex items-center gap-3 px-3 py-2 bg-gray-50 rounded-md">
                        <span className="text-xs font-medium text-gray-500 min-w-[80px]">{period.label}</span>
                        <span className="font-mono text-[11px] text-gray-600 flex-1">{period.hours}</span>
                        <span className="font-mono text-[11px] font-semibold text-indigo-600 bg-indigo-50 px-1.5 py-0.5 rounded">
                          x{period.multiplier}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Agent Configs */}
              {simulationConfig.agent_configs && simulationConfig.agent_configs.length > 0 && (
                <div className="border-t border-gray-200 pt-3">
                  <div className="flex justify-between items-center mb-3">
                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Agent Config</span>
                    <span className="font-mono text-[11px] bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">
                      {simulationConfig.agent_configs.length}
                    </span>
                  </div>
                  <div className="grid grid-cols-2 gap-3 max-h-[400px] overflow-y-auto pr-1">
                    {simulationConfig.agent_configs.map((agent) => (
                      <div key={agent.agent_id} className="bg-gray-50 border border-gray-200 rounded-md p-3.5 transition-all hover:border-gray-400 hover:bg-white">
                        {/* Agent Header */}
                        <div className="flex justify-between items-start mb-3 pb-3 border-b border-gray-100">
                          <div>
                            <span className="font-mono text-[10px] text-gray-400 block">Agent {agent.agent_id}</span>
                            <span className="text-sm font-semibold text-gray-900">{agent.entity_name}</span>
                          </div>
                          <div className="flex gap-1.5">
                            <span className="text-[10px] text-gray-500 bg-gray-100 px-2 py-0.5 rounded">{agent.entity_type}</span>
                            <span
                              className={`text-[10px] font-medium uppercase px-2 py-0.5 rounded ${
                                agent.stance === "supportive"
                                  ? "bg-green-50 text-green-600"
                                  : agent.stance === "opposing"
                                  ? "bg-red-50 text-red-600"
                                  : agent.stance === "observer"
                                  ? "bg-amber-50 text-amber-600"
                                  : "bg-gray-100 text-gray-500"
                              }`}
                            >
                              {agent.stance}
                            </span>
                          </div>
                        </div>

                        {/* Activity Timeline */}
                        {agent.active_hours && (
                          <div className="mb-3">
                            <span className="text-[10px] text-gray-400 uppercase tracking-wider block mb-1.5">Active Hours</span>
                            <div className="flex gap-[2px] h-4 bg-gray-100 rounded p-[3px]">
                              {Array.from({ length: 24 }, (_, h) => (
                                <div
                                  key={h}
                                  className={`flex-1 rounded-sm transition-all ${
                                    agent.active_hours?.includes(h)
                                      ? "bg-gradient-to-b from-indigo-500 to-indigo-400"
                                      : "bg-gray-200"
                                  }`}
                                  title={`${h}:00`}
                                />
                              ))}
                            </div>
                            <div className="flex justify-between mt-1 font-mono text-[9px] text-gray-400">
                              <span>0</span><span>6</span><span>12</span><span>18</span><span>24</span>
                            </div>
                          </div>
                        )}

                        {/* Behavior Params */}
                        <div className="space-y-2.5">
                          <div className="grid grid-cols-3 gap-2">
                            <div>
                              <span className="text-[10px] text-gray-400 block">Posts/hr</span>
                              <span className="font-mono text-xs font-semibold text-gray-600">{agent.posts_per_hour}</span>
                            </div>
                            <div>
                              <span className="text-[10px] text-gray-400 block">Comments/hr</span>
                              <span className="font-mono text-xs font-semibold text-gray-600">{agent.comments_per_hour}</span>
                            </div>
                            <div>
                              <span className="text-[10px] text-gray-400 block">Delay</span>
                              <span className="font-mono text-xs font-semibold text-gray-600">{agent.response_delay_min}-{agent.response_delay_max}min</span>
                            </div>
                          </div>
                          <div className="grid grid-cols-3 gap-2">
                            <div>
                              <span className="text-[10px] text-gray-400 block">Activity</span>
                              <div className="flex items-center gap-1.5">
                                <div
                                  className="h-1 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full"
                                  style={{ width: `${(agent.activity_level || 0) * 40}px`, minWidth: "4px", maxWidth: "40px" }}
                                />
                                <span className="font-mono text-xs font-semibold text-gray-600">
                                  {((agent.activity_level || 0) * 100).toFixed(0)}%
                                </span>
                              </div>
                            </div>
                            <div>
                              <span className="text-[10px] text-gray-400 block">Sentiment</span>
                              <span
                                className={`font-mono text-xs font-semibold ${
                                  (agent.sentiment_bias || 0) > 0
                                    ? "text-green-600"
                                    : (agent.sentiment_bias || 0) < 0
                                    ? "text-red-600"
                                    : "text-gray-500"
                                }`}
                              >
                                {(agent.sentiment_bias || 0) > 0 ? "+" : ""}
                                {agent.sentiment_bias?.toFixed(1)}
                              </span>
                            </div>
                            <div>
                              <span className="text-[10px] text-gray-400 block">Influence</span>
                              <span className="font-mono text-xs font-semibold text-indigo-600">
                                {agent.influence_weight?.toFixed(1)}
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Platform Configs */}
              {(simulationConfig.twitter_config || simulationConfig.reddit_config) && (
                <div className="border-t border-gray-200 pt-3">
                  <div className="mb-3">
                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Recommendation Algorithm Config</span>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    {simulationConfig.twitter_config && (
                      <div className="bg-gray-50 p-3.5 rounded-md">
                        <div className="mb-2.5 pb-2 border-b border-gray-200">
                          <span className="text-[13px] font-semibold text-gray-800">Platform 1: Feed / Timeline</span>
                        </div>
                        <div className="space-y-2">
                          {[
                            ["Recency Weight", simulationConfig.twitter_config.recency_weight],
                            ["Popularity Weight", simulationConfig.twitter_config.popularity_weight],
                            ["Relevance Weight", simulationConfig.twitter_config.relevance_weight],
                            ["Viral Threshold", simulationConfig.twitter_config.viral_threshold],
                            ["Echo Chamber", simulationConfig.twitter_config.echo_chamber_strength],
                          ].map(([label, value]) => (
                            <div key={label as string} className="flex justify-between items-center">
                              <span className="text-xs text-gray-500">{label}</span>
                              <span className="font-mono text-xs font-semibold text-gray-900">{value as number}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                    {simulationConfig.reddit_config && (
                      <div className="bg-gray-50 p-3.5 rounded-md">
                        <div className="mb-2.5 pb-2 border-b border-gray-200">
                          <span className="text-[13px] font-semibold text-gray-800">Platform 2: Topics / Community</span>
                        </div>
                        <div className="space-y-2">
                          {[
                            ["Recency Weight", simulationConfig.reddit_config.recency_weight],
                            ["Popularity Weight", simulationConfig.reddit_config.popularity_weight],
                            ["Relevance Weight", simulationConfig.reddit_config.relevance_weight],
                            ["Viral Threshold", simulationConfig.reddit_config.viral_threshold],
                            ["Echo Chamber", simulationConfig.reddit_config.echo_chamber_strength],
                          ].map(([label, value]) => (
                            <div key={label as string} className="flex justify-between items-center">
                              <span className="text-xs text-gray-500">{label}</span>
                              <span className="font-mono text-xs font-semibold text-gray-900">{value as number}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Config Reasoning */}
              {simulationConfig.generation_reasoning && (
                <div className="border-t border-gray-200 pt-3">
                  <div className="mb-3">
                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">LLM Config Reasoning</span>
                  </div>
                  <div className="space-y-2.5">
                    {simulationConfig.generation_reasoning
                      .split("|")
                      .slice(0, 2)
                      .map((reason, idx) => (
                        <div key={idx} className="bg-gray-50 p-3 rounded-md">
                          <p className="text-[13px] text-gray-600 leading-relaxed m-0">{reason.trim()}</p>
                        </div>
                      ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* ═══ Step 04: Initial Activation Orchestration ═══ */}
        <div className={phaseClass(3)}>
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center gap-3">
              <span className={stepNumClass(3)}>04</span>
              <span className="font-semibold text-sm">Initial Activation Orchestration</span>
            </div>
            {phase > 3 ? (
              <Badge variant="success">Complete</Badge>
            ) : phase === 3 ? (
              <Badge variant="processing">Orchestrating</Badge>
            ) : (
              <Badge variant="secondary">Waiting</Badge>
            )}
          </div>
          <p className="text-[10px] text-gray-400 font-mono mb-2">POST /api/simulation/prepare</p>
          <p className="text-xs text-gray-500 mb-4">
            Auto-generate initial activation events and hot topics based on narrative direction to guide the world&apos;s initial state
          </p>

          {simulationConfig?.event_config && (
            <div className="space-y-5 mt-4">
              {/* Narrative Direction */}
              {simulationConfig.event_config.narrative_direction && (
                <div className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm">
                  <span className="flex items-center gap-2 text-[13px] font-semibold text-gray-500 tracking-wider mb-3">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="url(#grad1)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M16.24 7.76L14.12 14.12L7.76 16.24L9.88 9.88L16.24 7.76Z" fill="url(#grad1)" stroke="url(#grad1)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      <defs><linearGradient id="grad1" x1="2" y1="2" x2="22" y2="22"><stop stopColor="#FF5722"/><stop offset="1" stopColor="#FF9800"/></linearGradient></defs>
                    </svg>
                    Narrative Direction
                  </span>
                  <p className="text-sm text-gray-700 leading-relaxed text-justify">{simulationConfig.event_config.narrative_direction}</p>
                </div>
              )}

              {/* Hot Topics */}
              {simulationConfig.event_config.hot_topics && simulationConfig.event_config.hot_topics.length > 0 && (
                <div>
                  <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider block mb-3">Initial Hot Topics</span>
                  <div className="flex flex-wrap gap-2">
                    {simulationConfig.event_config.hot_topics.map((topic) => (
                      <span key={topic} className="text-xs text-orange-600 bg-orange-50 px-2.5 py-1 rounded-full font-medium">
                        # {topic}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Initial Posts */}
              {simulationConfig.event_config.initial_posts && simulationConfig.event_config.initial_posts.length > 0 && (
                <div className="border-t border-gray-200 pt-4">
                  <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider block mb-3">
                    Initial Activation Sequence ({simulationConfig.event_config.initial_posts.length})
                  </span>
                  <div className="flex flex-col gap-4 pl-2 border-l-2 border-gray-100 mt-3">
                    {simulationConfig.event_config.initial_posts.map((post, idx) => (
                      <div key={idx} className="relative pl-5">
                        <div className="absolute left-0 top-3.5 w-3 h-[2px] bg-gray-300" />
                        <div className="bg-gray-50 p-3 rounded-md border border-gray-100">
                          <div className="flex justify-between mb-1.5">
                            <span className="text-[11px] font-bold text-gray-800 uppercase">{post.poster_type}</span>
                            <span className="flex items-center gap-1.5">
                              <span className="font-mono text-[10px] text-gray-500">Agent {post.poster_agent_id}</span>
                              <span className="font-mono text-[10px] text-gray-400">@{getAgentUsername(post.poster_agent_id)}</span>
                            </span>
                          </div>
                          <p className="text-xs text-gray-600 leading-relaxed m-0">{post.content}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* ═══ Step 05: Ready ═══ */}
        <div className={phaseClass(4)}>
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center gap-3">
              <span className={stepNumClass(4)}>05</span>
              <span className="font-semibold text-sm">Ready to Simulate</span>
            </div>
            {phase >= 4 ? <Badge variant="processing">Ready</Badge> : <Badge variant="secondary">Waiting</Badge>}
          </div>
          <p className="text-[10px] text-gray-400 font-mono mb-2">POST /api/simulation/start</p>
          <p className="text-xs text-gray-500 mb-4">Simulation environment prepared, ready to run</p>

          {/* Rounds Configuration */}
          {simulationConfig && autoGeneratedRounds && (
            <div className="border-t border-gray-200 pt-5 mb-4">
              <div className="flex justify-between items-center mb-5">
                <div>
                  <span className="text-sm font-semibold text-gray-900 block">Simulation Rounds</span>
                  <span className="text-xs text-gray-400">
                    Simulate{" "}
                    <span className="font-mono font-semibold text-gray-900 bg-gray-100 px-1.5 py-0.5 rounded mx-0.5">
                      {simulationConfig.time_config?.total_simulation_hours || "-"}
                    </span>{" "}
                    hours, each round ={" "}
                    <span className="font-mono font-semibold text-gray-900 bg-gray-100 px-1.5 py-0.5 rounded mx-0.5">
                      {simulationConfig.time_config?.minutes_per_round || "-"}
                    </span>{" "}
                    minutes
                  </span>
                </div>
                <label className="flex items-center gap-2 cursor-pointer px-2 py-1 rounded-full hover:bg-gray-50">
                  <input
                    type="checkbox"
                    className="hidden"
                    checked={useCustomRounds}
                    onChange={(e) => setUseCustomRounds(e.target.checked)}
                  />
                  <div className={`w-9 h-5 rounded-full relative transition-all ${useCustomRounds ? "bg-black" : "bg-gray-200"}`}>
                    <div className={`absolute top-0.5 w-4 h-4 bg-white rounded-full shadow transition-transform ${useCustomRounds ? "translate-x-[18px]" : "translate-x-0.5"}`} />
                  </div>
                  <span className={`text-xs font-medium ${useCustomRounds ? "text-gray-900" : "text-gray-500"}`}>Custom</span>
                </label>
              </div>

              {useCustomRounds ? (
                <div className="animate-in fade-in">
                  <div className="flex justify-between items-end mb-4">
                    <div className="flex items-baseline gap-1">
                      <span className="font-mono text-2xl font-bold text-black">{customMaxRounds}</span>
                      <span className="text-xs text-gray-500 font-medium">rounds</span>
                    </div>
                    <span className="font-mono text-[11px] text-gray-500 bg-gray-100 px-2 py-1 rounded">
                      Est. ~{Math.round(customMaxRounds * 0.6)} min (100 agents)
                    </span>
                  </div>
                  <div className="relative px-0.5">
                    <input
                      type="range"
                      value={customMaxRounds}
                      onChange={(e) => setCustomMaxRounds(parseInt(e.target.value))}
                      min={10}
                      max={autoGeneratedRounds}
                      step={5}
                      className="w-full h-1 bg-gray-200 rounded appearance-none cursor-pointer accent-black [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white [&::-webkit-slider-thumb]:border-2 [&::-webkit-slider-thumb]:border-black [&::-webkit-slider-thumb]:shadow [&::-webkit-slider-thumb]:cursor-pointer"
                    />
                    <div className="flex justify-between mt-2 font-mono text-[10px] text-gray-400 relative">
                      <span>10</span>
                      <span
                        className={`cursor-pointer hover:text-black ${customMaxRounds === 40 ? "text-black font-semibold" : ""}`}
                        onClick={() => setCustomMaxRounds(40)}
                      >
                        40 (recommended)
                      </span>
                      <span>{autoGeneratedRounds}</span>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="animate-in fade-in">
                  <div className="flex items-center gap-6 bg-gray-50 p-4 rounded-lg">
                    <div className="flex items-baseline gap-1 pr-6 border-r border-gray-200">
                      <span className="font-mono text-2xl font-bold text-black">{autoGeneratedRounds}</span>
                      <span className="text-xs text-gray-500 font-medium">rounds</span>
                    </div>
                    <div className="flex-1 space-y-2">
                      <span className="inline-flex items-center gap-1.5 font-mono text-[11px] text-gray-500 bg-white border border-gray-200 px-2 py-0.5 rounded-md shadow-sm">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                        Est. ~{Math.round(autoGeneratedRounds * 0.6)} min (100 agents)
                      </span>
                      <p
                        className="text-xs text-black font-medium cursor-pointer hover:underline m-0"
                        onClick={() => setUseCustomRounds(true)}
                      >
                        For first run, strongly recommend switching to Custom mode to reduce rounds for quick preview
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          <div className="grid grid-cols-2 gap-3 mt-4">
            <Button variant="outline" onClick={onGoBack}>
              &larr; Back to Graph
            </Button>
            <Button disabled={phase < 4} onClick={handleStartSimulation}>
              Start Simulation &rarr;
            </Button>
          </div>
        </div>
      </div>

      {/* ═══ Profile Detail Modal ═══ */}
      <Dialog open={!!selectedProfile} onOpenChange={(open) => { if (!open) setSelectedProfile(null) }}>
        <DialogContent className="max-w-[600px] max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <div className="flex items-baseline gap-2.5 mb-1">
              <DialogTitle className="text-xl font-bold">{selectedProfile?.username}</DialogTitle>
              <span className="font-mono text-[13px] text-gray-400">@{selectedProfile?.name}</span>
            </div>
            {selectedProfile?.profession && (
              <span className="text-xs text-gray-600 bg-gray-100 px-2.5 py-1 rounded inline-block font-medium">
                {selectedProfile.profession}
              </span>
            )}
          </DialogHeader>

          {selectedProfile && (
            <div className="space-y-6 mt-2">
              {/* Basic Info Grid */}
              <div className="grid grid-cols-2 gap-x-4 gap-y-5">
                {[
                  ["Age", selectedProfile.age ? `${selectedProfile.age}` : "-"],
                  ["Gender", selectedProfile.gender === "male" ? "Male" : selectedProfile.gender === "female" ? "Female" : selectedProfile.gender || "-"],
                  ["Country", selectedProfile.country || "-"],
                  ["MBTI", selectedProfile.mbti || "-"],
                ].map(([label, value]) => (
                  <div key={label as string}>
                    <span className="text-[11px] text-gray-400 uppercase tracking-wider font-semibold block mb-1">{label}</span>
                    <span className={`text-[15px] font-semibold text-gray-800 ${label === "MBTI" ? "font-mono text-orange-600" : ""}`}>
                      {value}
                    </span>
                  </div>
                ))}
              </div>

              {/* Bio */}
              <div>
                <span className="text-[11px] text-gray-400 uppercase tracking-wider font-semibold block mb-2">Profile Bio</span>
                <p className="text-sm text-gray-700 leading-relaxed bg-gray-50 p-4 rounded-md border-l-[3px] border-gray-300 m-0">
                  {selectedProfile.bio || "No bio available"}
                </p>
              </div>

              {/* Topics */}
              {selectedProfile.interested_topics && selectedProfile.interested_topics.length > 0 && (
                <div>
                  <span className="text-[11px] text-gray-400 uppercase tracking-wider font-semibold block mb-2">Related Topics</span>
                  <div className="flex flex-wrap gap-2">
                    {selectedProfile.interested_topics.map((topic) => (
                      <span key={topic} className="text-[11px] text-blue-700 bg-blue-50 px-2.5 py-1 rounded-full hover:bg-blue-100 transition-colors">
                        {topic}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Detailed Persona */}
              {selectedProfile.persona && (
                <div>
                  <span className="text-[11px] text-gray-400 uppercase tracking-wider font-semibold block mb-2">Detailed Persona</span>
                  <div className="grid grid-cols-2 gap-3 mb-3">
                    {[
                      ["Event Experience", "Complete behavioral trajectory in this event"],
                      ["Behavior Pattern", "Summarized experience and style preferences"],
                      ["Memory Imprint", "Memories formed from real-world seeds"],
                      ["Social Network", "Individual connections and interaction graph"],
                    ].map(([title, desc]) => (
                      <div key={title as string} className="bg-gray-50 p-3 rounded-md border-l-[3px] border-gray-300 hover:border-gray-500 hover:bg-gray-100 transition-all">
                        <span className="text-xs font-bold text-gray-800 block mb-1">{title}</span>
                        <span className="text-[10px] text-gray-500 leading-snug">{desc}</span>
                      </div>
                    ))}
                  </div>
                  <p className="text-[13px] text-gray-600 leading-relaxed text-justify m-0">
                    {selectedProfile.persona}
                  </p>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* ═══ System Logs ═══ */}
      <div className="bg-black text-gray-300 p-4 font-mono border-t border-gray-800 flex-shrink-0">
        <div className="flex justify-between border-b border-gray-800 pb-2 mb-2 text-[10px] text-gray-600">
          <span>SYSTEM DASHBOARD</span>
          <span>{simulationId || "NO_SIMULATION"}</span>
        </div>
        <div ref={logRef} className="flex flex-col gap-1 h-20 overflow-y-auto pr-1">
          {systemLogs.map((log, i) => (
            <div key={i} className="text-[11px] flex gap-3 leading-relaxed">
              <span className="text-gray-600 min-w-[75px]">{log.time}</span>
              <span className="text-gray-400 break-all">{log.msg}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
